host: 128.97.32.120
author:           'Jon Van Lew'
title:            'Little Black Dog Blog'
description:      '& the art of over engineering'
disqus_shortname: jonnyvlreport
share:            true
dropcap:			true
locale: en_US
logo:             Molly_Small.png
baseurl:        	  


avatar:         'jtvanlew.jpg'
email:          jtvanlew@ucla.edu

twitter_username:        jtvanlew
facebook_username:       jtvanlew
github_username:         jtvanlew      
instagram_username:      jtvanlew
# For Google Authorship https://plus.google.com/authorship
google_plus_username:    https://plus.google.com/+JonVanLew/

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-24714334-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in footer navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Categories
    url: /categories
  - title: About
    url: /about
  - title: Travel Photos
    url: /photos/maps/
  # - title: Work
  #   url: /page/xively-temp/


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

prose:
  rooturl: '_posts'
  siteurl: 'http://jtvanlew.github.io/'
  relativeLinks: 'http://jtvanlew.github.io/links.jsonp'
  media: 'images'
  metadata:
    _posts:
      - name: "published"
        field:
          label: "Published"
          element: "checkbox"
          value: "true"
      - name: "layout"
        field:
          element: "hidden"
          label: "Layout"
          value: "post"
      - name: "title"
        field:
          label: "Title"
          element: "text"
          value: "An Awesome Headline!"
      - name: "description"
        field:
          element: "text"
          label: "Description"
          placeholder: "Enter Post Description"
      - name: "headline"
        field:
          element: "text"
          label: "headline"
          placeholder: "Enter Post Headline"
      - name: "modified"
        field:
          element: "text"
          label: "Has this page been modified?"
          placeholder: "YYYY-MM-DD"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add categories"
          placeholder: "Choose categories"
          value: personal
          options:
            - name: "Personal"
              value: personal
            - name: "Engineering"
              value: engineering
            - name: "Bicycling"
              value: bicycling
            - name: "Coffee"
              value: coffee
            - name: "Travel"
              value: travel
            - name: "Programming"
              value: programming
            - name: "Brewing"
              value: brewing
          alterable: true
      - name: "tags"
        field:
          element: "text"
          label: "Tags"
          placeholder: "Enter tags, separated by spaces"
      - name: "imagefeature"
        field:
          element: "text"
          label: "Featured Image"
          placeholder: "somefile.jpg"
      - name: "mathjax"
        field:
          element: "checkbox"
          label: "MathJax"
          value: false
      - name: "comments"
        field:
          element: "checkbox"
          label: "Allow comments"
          value: true
      - name: "share"
        field:
          element: "checkbox"
          label: "Allow shoaring"
          value: true
      - name: "chart"
        field:
          element: "checkbox"
          label: "Add post to chart"
          value: true

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
